services:
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "54329:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fred
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
